In [ ]:
# ================================
# DAY 1 — NUMPY EXERCISES
# ================================


5

In [2]:
import numpy as np 
# =========================================
# 🟢 LEVEL 1: FUNDAMENTALS
# =========================================

# 1. Create a NumPy array: [0, 1, 2, ..., 19]
# Your code:

In [3]:
Z = np.arange(20)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
# 2. Create a 4x4 matrix filled with zeros
# Your code:
Y = np.zeros(4)
L = np.array( [[Y], [Y], [Y], [Y]]).reshape(4,4)

L



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
#3. Create 10 evenly spaced numbers between 0 and 5
# Your code:
LN = np.linspace(0,5,10)
LN

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
# =========================================
# 🟡 LEVEL 2: CORE SKILLS
# =========================================

# 4. Create np.arange(12) and reshape it into a 3x4 matrix
# Your code:
OL = np.arange(12).reshape(3,4)

OL

# -----------------------------------------

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
# 5. Indexing Practice
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

# Extract:
# a) second row
# b) last column
# c) middle element (50)

# Your code:
arr[1]
arr[0: , 2] 
arr[1][1]
# -----------------------------------------

np.int64(50)

In [46]:
# 6. Add 50 to every element of the array (no loops)
# Your code:

arr + 50
# -----------------------------------------

array([[ 60,  70,  80],
       [ 90, 100, 110],
       [120, 130, 140]])

In [53]:
# =========================================
# 🔴 LEVEL 3: REAL THINKING
# =========================================

# 8. Boolean masking
arr = np.arange(1, 21)

# a) return only even numbers
# b) return only numbers greater than 10
# Your code:
R = arr[arr %2 == 0]
O = arr[arr > 10]
O

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 9. Random + statistics

# Create 1000 random numbers between 0 and 1
# Then compute:
# - mean
# - standard deviation
# - count how many values > 0.7

# Your code:
STAT = np.random.rand(1000)
STAT.mean()
STAT.std()
V = np.sum(STAT> 0.7)


np.int64(293)

In [73]:
# 10. Normalize array to range [0,1]

arr = np.array([10,20,30,40])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

# Your code:
normalized


array([0.        , 0.33333333, 0.66666667, 1.        ])

In [72]:
# =========================================
# 🧠 MINI CHALLENGE
# =========================================

# 11. Apply:
# - 20% discount
# - then 8% tax
# in ONE LINE

prices = np.array([100, 150, 200, 250])

(prices * 0.20) * 1.08

# Your code:


array([21.6, 32.4, 43.2, 54. ])