In [ ]:
# ================================
# DAY 1 — NUMPY EXERCISES
# ================================


5

In [2]:
import numpy as np 
# =========================================
# 🟢 LEVEL 1: FUNDAMENTALS
# =========================================

# 1. Create a NumPy array: [0, 1, 2, ..., 19]
# Your code:

In [3]:
Z = np.arange(20)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 2. Create a 4x4 matrix filled with zeros
# Your code:
Y = np.zeros((4,4))


Y



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#3. Create 10 evenly spaced numbers between 0 and 5
# Your code:
LN = np.linspace(0,5,10)
LN

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
# =========================================
# 🟡 LEVEL 2: CORE SKILLS
# =========================================

# 4. Create np.arange(12) and reshape it into a 3x4 matrix
# Your code:
OL = np.arange(12).reshape(3,4)

OL

# -----------------------------------------

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
# 5. Indexing Practice
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

# Extract:
# a) second row
# b) last column
# c) middle element (50)

# Your code:
A = arr[1]
B = arr[0: , 2] 
C = arr[1][1]
# -----------------------------------------
A, B, C

(array([40, 50, 60]), array([30, 60, 90]), np.int64(50))

In [46]:
# 6. Add 50 to every element of the array (no loops)
# Your code:

arr + 50
# -----------------------------------------

array([[ 60,  70,  80],
       [ 90, 100, 110],
       [120, 130, 140]])

In [3]:
# 7. Multiply each row by [1, 10, 100]

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr * np.array([1, 10, 100])

array([[  10,  200, 3000],
       [  40,  500, 6000],
       [  70,  800, 9000]])

In [4]:
# =========================================
# 🔴 LEVEL 3: REAL THINKING
# =========================================

# 8. Boolean masking
arr = np.arange(1, 21)

# a) return only even numbers
# b) return only numbers greater than 10
# Your code:
R = arr[arr %2 == 0]
O = arr[arr > 10]
O, R

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]))

In [5]:
# 9. Random + statistics

# Create 1000 random numbers between 0 and 1
# Then compute:
# - mean
# - standard deviation
# - count how many values > 0.7

# Your code:
STAT = np.random.rand(1000)
STAT.mean()
STAT.std()
V = np.sum(STAT> 0.7)

STAT, STAT.mean(), STAT.std(), V

(array([1.33760992e-01, 3.13807668e-02, 9.68902334e-01, 8.88077754e-01,
        7.63285817e-01, 8.95887868e-01, 8.16185319e-03, 5.32409401e-02,
        8.93251330e-01, 3.67996692e-02, 2.20206097e-01, 3.36434130e-01,
        3.30324057e-01, 3.61936403e-01, 6.86766527e-01, 7.95161453e-01,
        7.89399960e-01, 3.36608319e-01, 4.59216316e-02, 2.19236138e-01,
        4.44838411e-01, 9.85468642e-01, 6.76758139e-01, 5.46250350e-01,
        7.74756650e-01, 3.17440220e-01, 5.60242540e-01, 3.66148818e-01,
        1.22083000e-01, 6.96709352e-01, 2.35041770e-01, 7.13572212e-01,
        5.68765367e-01, 1.54267644e-01, 3.75891704e-01, 9.69101398e-01,
        6.29586511e-01, 1.47277471e-01, 7.47608248e-01, 3.23941759e-01,
        1.56831243e-01, 7.29702084e-01, 6.27210395e-01, 9.53815854e-01,
        4.25544294e-01, 1.66714531e-01, 4.04432579e-01, 4.46973807e-01,
        2.89775489e-01, 6.88319756e-01, 8.11416537e-02, 7.58963264e-01,
        8.32559218e-01, 4.06506015e-01, 2.92123838e-01, 1.749804

In [73]:
# 10. Normalize array to range [0,1]

arr = np.array([10,20,30,40])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

# Your code:
normalized


array([0.        , 0.33333333, 0.66666667, 1.        ])

In [6]:
# =========================================
# 🧠 MINI CHALLENGE
# =========================================

# 11. Apply:
# - 20% discount
# - then 8% tax
# in ONE LINE

prices = np.array([100, 150, 200, 250])

(prices * 0.80) * 1.08

# Your code:


array([ 86.4, 129.6, 172.8, 216. ])